### ISSUE TITLE
Gemstone Power Scrolls

### ISSUE THREAD

**Issue by k-tten** [Altpapier/SkyHelper-Networth#27]
Hi yall, am I just tripping or does this not include [gemstone power scrolls](https://wiki.hypixel.net/Power_Scrolls)?

If it's intentional, could you explain why?

If not, could you add it? I'm not sure about the coefficient yet...

Thanks.

**Comment by MattTheCuber** [comment]
You are correct, we will probably add this. @Altpapier what percentage worth should this be?

**Comment by k-tten** [comment]
I'm thinking around 0.75 since the scrolls do provide a significant enhancement to the efficacy of an item, say, putting a ruby power scroll onto a wand of atonement.

**Comment by Altpapier** [comment]
If we decide to add it we will have to do something different than just using the price of the item as they are often way more expensive on the ah than if you were to craft them yourself (often double the price) @MattTheCuber what do you think

**Comment by MattTheCuber** [comment]
Here's the current data:

| **Scroll Type** | **Craft Cost** | **Average Sale Value** | **Difference** |
|-----------------|----------------|------------------------|----------------|
| **Ruby**        | 405,150        | 690,000                | 70%            |
| **Opal**        | 961,890        | 1,600,000              | 66%            |
| **Amber**       | 513,460        | 700,000                | 36%            |
| **Jasper**      | 1,390,000      | 1,700,000              | 22%            |
| **Amethyst**    | 556,370        | 899,000                | 62%            |
| **Sapphire**    | 522,910        | 650,000                | 24%            |
|                 |                | **Average Difference** | **47%**        |

Quite a bit above craft cost... Not sure on this one.

**Comment by k-tten** [comment]
Most people who want to apply scrolls don't have the requirement to craft it. You could possibly use a weighted average between craft cost and average sale to account for the disproportionate amount of people that can craft it themselves and use it. Or straight up average the values.

**Comment by k-tten** [comment]
For the applied cost I think around 50-75% would be best as small upgrades to items (<1m) are usually overlooked.

**Comment by MattTheCuber** [comment]
@Altpapier I think we could add it with 50% (maybe higher) application value as that is the average difference. And, as he said, crafting requirements play a factor (Requires Gemstone Collection 7).

**Comment by Altpapier** [comment]
> @Altpapier I think we could add it with 50% (maybe higher) application value as that is the average difference. And, as he said, crafting requirements play a factor (Requires Gemstone Collection 7).

sure

**Comment by MattTheCuber** [comment]
Ok, will do this week sometime

**Comment by MattTheCuber** [comment]
![image](https://github.com/Altpapier/SkyHelper-Networth/assets/32849887/36efb529-80c6-4890-a7f1-088ca6e32616)
