### ISSUE TITLE
ItemNetworth From NBT data

### ISSUE THREAD

**Issue by neilhuang007** [Altpapier/SkyHelper-Networth#34]
Hi,
I am currently working on a auction flipper and i have obtained the rarity, uuid, catagory and NBT value of a item, is it possible for me to use these data and use ur networth calculator?

**Comment by DuckySoLucky** [comment]
Heya, you can obtain item networth by passing item's NBT into `getItemNetworth()` function. You can read more abotu that at  [docs](https://github.com/Altpapier/SkyHelper-Networth?tab=readme-ov-file#getitemnetworth)

lmk if you have any other questions

**Comment by neilhuang007** [comment]
Hi,
    thanks for the help, i am still struggling with this, would you mind if you take a look at my code? res:https://github.com/neilhuang007/auctionflipper  on item evaluator bassically passed in a base64 and decoded it to NBT, then when passed to Evaluate.js it says that Invalid item provided
thanks

**Comment by neilhuang007** [comment]
@DuckySoLucky

**Comment by DuckySoLucky** [comment]
> Hi, thanks for the help, i am still struggling with this, would you mind if you take a look at my code? res:https://github.com/neilhuang007/auctionflipper on item evaluator bassically passed in a base64 and decoded it to NBT, then when passed to Evaluate.js it says that Invalid item provided thanks

you need to pass in `input.i[0]`, so the `i` property of input and the first element
