### ISSUE TITLE
[Bug Report] Wrong type of accessories calculations

### ISSUE THREAD

**Issue by ench233** [Altpapier/SkyHelper-Networth#37]
![image](https://github.com/user-attachments/assets/cbbf1d28-8ee6-4ee0-9119-0c1c1b475a05)
like this image, the highest valued accessories enrichment were wrongly marked as r3k, this issue just happened on the highest valued accessories, and others were marked correctly as 'talisman_enrichment'

**Comment by DuckySoLucky** [comment]
Heya, thanks for the report. Can you provide the example profile on which that happens?

**Comment by ench233** [comment]
thx for reply. here's example profile: 644ef38b50794423995df9fdca3d121c, playeruuid: 1dea7046c9e3498cabca5bf5ec1bed32

**Comment by DuckySoLucky** [comment]
I cannot seem to reproduce it? Can you join the [support server](https://discord.gg/4gUp4gHfcu) and open a ticket so it's easier and faster to communicate

![image](https://github.com/user-attachments/assets/4c8db3b1-8c7f-4479-88c5-581fd14a6bf2)

**Comment by ench233** [comment]
ok, i will join

**Comment by ench233** [comment]
The problem miraculously disappeared after I switched to WebStorm, so if you encounter this problem, why don't you switch to WebStorm too haha
